spring.application.name=demo
server.port=8080

# H2
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/polarisdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=


# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#datos de prueba
spring.jpa.generate-ddl=true
#persistente
spring.jpa.hibernate.ddl-auto=update

#loggin
#imprimir querry
loggin.level.org.hibernate.SQL=DEBUG
#imprime
loggin.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

server.error.whitelabel.enabled=false